export const UI_START_LOADING = 'ui-start-loading';
export const UI_STOP_LOADING = 'ui-stop-loading';

export const SET_APP_INTRO = 'SET_APP_INTRO';

export const SET_CONFIRMED_ACCOUNT = 'SET_CONFIRMED_ACCOUNT';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const SET_REAL_ESTATES = 'SET_REAL_ESTATES';
export const SET_REAL_ESTATE_DETAILS = 'SET_REAL_ESTATE_DETAILS';
export const SET_REAL_ESTATES_UNITS = 'SET_REAL_ESTATES_UNITS';
export const SET_REAL_ESTATES_CONTRACTS = 'SET_REAL_ESTATES_CONTRACTS';
export const SET_REAL_ESTATE_OUTGOINGS = 'SET_REAL_ESTATE_OUTGOINGS';

export const SET_CONTRACTS = 'SET_CONTRACTS';
export const SET_CONTRACT_DETAILS = 'SET_CONTRACT_DETAILS';
export const SET_ACTIVE_CONTRACT = 'SET_ACTIVE_CONTRACT';

export const SET_FINANCIAL_STATEMENT = 'SET_FINANCIAL_STATEMENT';
export const SET_DUE_PAYMENTS = 'SET_DUE_PAYMENTS';
export const SET_OUTGOINGS_DOCS = 'SET_OUTGOINGS_DOCS';

export const SET_FINANCIAL_STATISTICS = 'SET_FINANCIAL_STATISTICS';
export const SET_STATISTICS = 'SET_STATISTICS';

export const SET_RENTER_INFO = 'SET_RENTER_INFO';
